site_name: The Crystal Caravans
theme:
  name: material
  icon:
    logo: material/palm-tree
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - table-reader
  - print-site

